#version 460 core

#define WORKGROUP_X 32
#define WORKGROUP_Y 32
#define WORKGROUP_Z 1

layout(local_size_x = WORKGROUP_X, local_size_y = WORKGROUP_Y, local_size_z = WORKGROUP_Z) in;

// used both for read and write
layout(binding = 0, r32f) uniform image2D solution;

// indicates what pass is now: red or black
uniform int redBlack;

// TODO : shared memory

// f-function
float f(float x, float y)
{
	float xxpyy = x * x + y * y;
	return 4.0 * (xxpyy - 1.0) * exp(-xxpyy);
}


void main()
{
	ivec2 ij = ivec2(gl_GlobalInvocationID.xy);

	float uij = imageLoad(solution, ij).x;
	float uijm1 = imageLoad(solution, ij + ivec2(0, -1)).x;
	float uijp1 = imageLoad(solution, ij + ivec2(0, +1)).x;
	float uim1j = imageLoad(solution, ij + ivec2(-1, 0)).x;
	float uip1j = imageLoad(solution, ij + ivec2(+1, 0)).x;
}